memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 300
max_input_time = 300

; CA recommended settings
date.timezone = Australia/Hobart
always_populate_raw_post_data = -1

; Extensions
extension=gd
extension=intl
extension=mbstring
extension=xml
extension=zip
extension=curl
extension=mysqli
extension=pdo_mysql
extension=exif
extension=fileinfo
